version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: briohr-mongodb-dev
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
